

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-helm
    app.kubernetes.io/managed-by: Helm
  name: my-helm
spec:
  type: {{ .Values.service.type }}
  ports:
  - port : 80
